version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run serve -- --host 0.0.0.0

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile.backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend/data:/app/data  
        - ./backend:/app
      environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432/kupivozi
        - DEBUG=True
      depends_on:
        db:
          condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=kupivozi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

volumes:
  postgres_data: