# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/data/import

VOLUME /app/data 

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py import_vehicles && python manage.py runserver 0.0.0.0:8000"]
